# Generated by Django 3.1.12 on 2022-04-14 13:52

import django.core.validators
from django.db import migrations, models
import djongo.models.fields
import stt.models
import stt.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranscribedClip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.FileField(upload_to=stt.utils.UUIDFileName('clips/%Y/%m/%d/'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'wave', 'flac', 'mp3', 'm4a', 'mp4'])])),
                ('transcription', models.TextField(blank=True)),
                ('ratings', djongo.models.fields.ArrayField(default=[], model_container=stt.models.Rating)),
            ],
            options={
                'db_table': 'transcribedclips',
            },
        ),
    ]
